filegroup(
    name = "prompt_assets",
    srcs = glob(["*.txt"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "system_prompt_asset",
    srcs = ["system_prompt.txt"],
    visibility = ["//visibility:public"],
)
