#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <string_view>
#include <vector>

namespace {

constexpr std::string_view kPromptsRoot = "server/memory/include/prompts/";
constexpr std::string_view kGeneratedHeaderPreamble =
    "// Generated by embed_prompts_tool.cpp. Do not edit manually.\n"
    "inline constexpr EmbeddedPromptAsset kEmbeddedPromptAssets[] = {\n";

std::string NormalizePath(std::string path) {
    std::replace(path.begin(), path.end(), '\\', '/');
    return path;
}

std::string RunfilePathFor(const std::filesystem::path& source_path) {
    const std::string normalized = NormalizePath(source_path.generic_string());
    const std::size_t marker_index = normalized.find(kPromptsRoot);
    if (marker_index == std::string::npos) {
        throw std::runtime_error("unable to derive runfile path for prompt source");
    }
    return normalized.substr(marker_index);
}

std::string ReadFile(const std::filesystem::path& source_path) {
    std::ifstream stream(source_path, std::ios::binary);
    if (!stream.is_open()) {
        throw std::runtime_error("unable to open prompt source");
    }
    return std::string(std::istreambuf_iterator<char>(stream), std::istreambuf_iterator<char>());
}

std::string EscapeStringLiteral(std::string_view text) {
    std::string escaped;
    escaped.reserve(text.size());
    for (const char ch : text) {
        switch (ch) {
        case '\\':
            escaped.append("\\\\");
            break;
        case '"':
            escaped.append("\\\"");
            break;
        default:
            escaped.push_back(ch);
            break;
        }
    }
    return escaped;
}

std::string RawStringDelimiter(std::string_view text, std::size_t index) {
    std::string delimiter = "P" + std::to_string(index);
    while (text.find(")" + delimiter + "\"") != std::string_view::npos) {
        delimiter.push_back('X');
        if (delimiter.size() > 16U) {
            throw std::runtime_error("unable to find raw string delimiter within MSVC limit");
        }
    }
    return delimiter;
}

struct PromptSource {
    std::string runfile_path;
    std::string content;
};

} // namespace

int main(int argc, char** argv) {
    if (argc < 3) {
        std::cerr << "usage: embed_prompts_tool <output> <prompt> [<prompt> ...]\n";
        return 1;
    }

    try {
        const std::filesystem::path output_path(argv[1]);
        std::vector<PromptSource> prompts;
        prompts.reserve(static_cast<std::size_t>(argc - 2));
        for (int i = 2; i < argc; ++i) {
            const std::filesystem::path source_path(argv[i]);
            prompts.push_back(PromptSource{
                .runfile_path = RunfilePathFor(source_path),
                .content = ReadFile(source_path),
            });
        }
        std::sort(prompts.begin(), prompts.end(),
                  [](const PromptSource& lhs, const PromptSource& rhs) {
                      return lhs.runfile_path < rhs.runfile_path;
                  });

        std::ofstream output(output_path, std::ios::binary | std::ios::trunc);
        if (!output.is_open()) {
            std::cerr << "unable to open generated output file\n";
            return 1;
        }

        output << kGeneratedHeaderPreamble;
        for (std::size_t i = 0; i < prompts.size(); ++i) {
            const PromptSource& prompt = prompts[i];
            const std::string delimiter = RawStringDelimiter(prompt.content, i);
            output << "    {\n";
            output << "        \"" << EscapeStringLiteral(prompt.runfile_path) << "\",\n";
            output << "        R\"" << delimiter << "(" << prompt.content << ")" << delimiter
                   << "\",\n";
            output << "    },\n";
        }
        output << "};\n";
        if (!output.good()) {
            std::cerr << "failed while writing generated prompt header\n";
            return 1;
        }
    } catch (const std::exception& error) {
        std::cerr << error.what() << '\n';
        return 1;
    }

    return 0;
}
