load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "shared_headers",
    hdrs = ["build_info.hpp"],
    strip_include_prefix = "/shared/include",
    visibility = ["//visibility:public"],
)
