load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "render",
    hdrs = [
        "model_renderer.hpp",
        "render_types.hpp",
        "render_world.hpp",
        "renderer_backend.hpp",
    ],
    strip_include_prefix = "/engine/include",
    visibility = ["//visibility:public"],
)
