load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "engine_headers",
    hdrs = ["bootstrap.hpp"],
    strip_include_prefix = "/engine/include",
    visibility = ["//visibility:public"],
)
